<a href="https://colab.research.google.com/github/Gore-999/Machine-learning/blob/main/day-3%20numpy_5th_sem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#introduction to Numpy

#what will we cover?
#-creating single dimensional arrays✅
#-multidimensional array
#-randomly generated array
#-element wise operations
#-element wise operations
#-summarizing operations

###Single Dimensional array




In [ ]:
import numpy as np

In [ ]:
# create an array with all the elemens to be zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [ ]:
# create an array with all the elements to be ones
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# create an array of size 10 with all elements 3
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
# create a random array a user can give
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [ ]:
# create an array user gives a range
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
# create an array with evenly space numbers within a specified range
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
# create an array with evenly space numbers within a specified range
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

###Multi Dimensional Array


In [ ]:
np.zeros([3, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones([3, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[0, 1] = 20
a

array([[20, 20, 20],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
a[0:1] = 20
print(a)

[[20 20 20]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
a[2] = [1, 1, 1]
a

array([[20, 20, 20],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [ ]:
a[:, 2] = [2, 2, 2]
a

array([[20, 20,  2],
       [ 4,  5,  2],
       [ 1,  1,  2]])

In [ ]:
np.full([3, 3], 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

###randomly generated array

  -Numpy can create arrays filled with random numbers.
  -To ensure the reproductibility, you can set a seed using ```np.random.seed() . It will generate the exact some random numbers for executions.
  -if you removeor change the seed values, the sequence of random numbers will be changed.

In [ ]:
np.random.rand(5)

array([0.76363755, 0.78673187, 0.40600403, 0.81951216, 0.53178421])

In [ ]:
np.random.seed(80)
np.random.rand(5)

array([0.52191572, 0.69940637, 0.26986897, 0.67448187, 0.90807208])

In [ ]:
np.random.randn(5, 2)

array([[-1.03446493,  0.66424004],
       [-1.13937438, -0.89472205],
       [-0.2207972 , -0.43007258],
       [ 1.19972246,  0.1222967 ],
       [ 0.54794733, -0.52658091]])

In [ ]:
np.random.randint(low=0, high=100, size=(5, 2))

array([[ 7, 69],
       [96, 56],
       [15,  3],
       [94, 39],
       [51, 94]])

#element wise operation on entire arrays element by element

In [2]:
import numpy as np
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [3]:
b = (10 + (a*2))
b

array([10, 12, 14, 16, 18])

In [6]:
# comparison operations
a


array([0, 1, 2, 3, 4])

In [7]:
a >= 2

array([False, False,  True,  True,  True])

In [8]:
a > b

array([False, False, False, False, False])

In [9]:
# summarizing of the data
# numpy provides functions for summarizing array data
a

array([0, 1, 2, 3, 4])

In [10]:
a.std()

1.4142135623730951

In [12]:
a.sum()

10

In [14]:
a.min()

0

In [15]:
a.max()

4